# Generated by Django 5.0.11 on 2025-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
