# Generated by Django 5.0.11 on 2025-02-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keycloak_id',
        ),
    ]
